Repository UBC-MDS/mds_array_manipulation, pull requests merged in 2024-01, with the labels that each got.

#12 Update CONDUCT.md
  CONDUCT.md
Labels: documentation

#17 Contributing docs
  CONTRIBUTING.md
  CONTRIBUTORS.md
Labels: documentation

#19 6 readme creation
  README.md
Labels: documentation

#18 Added argmax function
  src/mds_array_manipulation/mds_array_manipulation.py
Labels: enhancement

#20 Update README
  README.md
Labels: documentation

#22 add github action
  .github/workflows/ci-cd.yml
Labels: enhancement

#36 Added test_argmax.py and added fixture none_numpy_array in conftest.py
  tests/conftest.py
  tests/test_argmax.py
Labels: enhancement

#39 Sort array implementation
  src/mds_array_manipulation/mds_array_manipulation.py
  src/mds_array_manipulation/sort_array.py
  tests/conftest.py
  tests/test_mds_array_manipulation.py
  tests/test_sort_array.py
Labels: enhancement

#41 Added argmax function and fixed mds_array_manipulation.py
  src/mds_array_manipulation/argmax.py
  src/mds_array_manipulation/mds_array_manipulation.py
Labels: enhancement

#47 Fixed test_argmax.py by correcting right answer (due to confusion on axis)
  tests/test_argmax.py
Labels: bug

#49 Deleted mds_array_manipulation.py and deleted test_mds_array_manipulation.py as they are duplicated
  src/mds_array_manipulation/mds_array_manipulation.py
  tests/test_mds_array_manipulation.py
Labels: duplicate

#48 Updated test_argmax.py : Deleted unnecessary comment
  tests/test_argmax.py
Labels: duplicate

#54 modify functions and tests
  src/mds_array_manipulation/count_nonzero_elements.py
  src/mds_array_manipulation/search_array.py
  tests/test_count_nonzero_elements.py
  tests/test_search_array.py
Labels: enhancement

#55 Updated Readme with virtual environment commands
  README.md
Labels: documentation

#61 adding sort_array usage in example.ipynb
  docs/example.ipynb
  poetry.lock
  pyproject.toml
Labels: documentation

#63 update count_nonzero doc and add pyarrow in poetry
  docs/example.ipynb
  poetry.lock
  pyproject.toml
Labels: enhancement

#64 Added Argmax document on example.ipynb file
  docs/example.ipynb
Labels: documentation

#81 fix: Feedback addressed by added badges and improved summary on README.md
  README.md
Labels: documentation
