Repository UBC-MDS/mds_array_manipulation, pull requests merged in 2024-02, with the labels that each got.

#82 fix: Feedback addressed by added badges and improved summary on README.md - 2
  README.md
Labels: documentation

#83 fix: Feedback addressed by added badges and improved summary on README.md - 3
  README.md
Labels: documentation

#85 Function docs
  src/mds_array_manipulation/count_nonzero_elements.py
  src/mds_array_manipulation/search_array.py
  src/mds_array_manipulation/sort_array.py
Labels: documentation, enhancement

#84 fix: Feedback addressed by updating table formatting in Vignette
  docs/example.ipynb
Labels: enhancement

#89 66 review license file
  LICENSE
  README.md
Labels: documentation

#92 fix: Adjusted License part on README.md
  README.md
Labels: documentation

#91 feat : Adjusted LICENSE (Added CC-by-SA-4.0)
  LICENSE
Labels: documentation, enhancement

#96 fix: Feedback addressed by updating command in Readme
  README.md
Labels: documentation

#97 fix: Feedback addressed by adding pypi link
  README.md
Labels: documentation
